### ISSUE TITLE
12 user stories

### ISSUE THREAD

**Issue by EnRangel** [caitlinsusbilla/CST438_Project1_Grp1#5]
As a user, I want to be able to login in to look at my profile page to see what Pokemon are in my team.
API: PokeApi

As a user, I want to be able to go to the pokedex page to see all the Pokemon that are available to add to my team.
API: PokeApi

As a user, I want to be able to see what other users on the app have in their Pokemon team.

As a user, I want to be able to search Pokemon by specific types or names to make it easier to look for the ones I know I want.
API: PokeApi

As a user, I want to be able to click on a Pokemon to get more general information about it.
API: PokeApi

As a user, I want to be able to vote on the other players team through leader boards.

As a user, I want to be able to add, delete, give nicknames to the Pokemon in my team like in the game.

**Comment by SGalindo831** [comment]
As a user, I want to be able to add and remove any Pokemon I want.

As a user, I want my Pokémon team to be saved when I log out and log back in so that I don’t lose my progress.

As a user, I want to filter the list of Pokémon by their type (e.g., water, fire, grass) so that I can focus on building a type-specific team.

**Comment by aharo1110** [comment]
As a user, I want to be able to look at different evolutions of the same Pokemon and see their characteristics.
API: PokeAPI

As a user, I want to be able to create a user account to allow other people to search me up and find my team and to keep my team secure.

As a user, I want the interface to be easy to use and also comfortable so that I can have a good user experience.

**Comment by caitlinsusbilla** [comment]
As a user, I want to see recommended/popular Pokemon teams.

As a user, I want to be able to edit my profile.

As a user, I want to be able to save/bookmark Pokemon I am interested in.
